name: Create Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set pull request template
        run: |
          TEMPLATE=$(cat .github/bug_pr_template.md)
          echo "${TEMPLATE}" > "$GITHUB_WORKSPACE/.github/PULL_REQUEST_TEMPLATE.md"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
          title: ${{ github.event.pull_request.title }}
          body: |
            ${{ env.TEMPLATE }}
